baseURL: https://vishruthdevan.me/
title: Vishruth Devan
pagerSize: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-B286V2NHY6

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Vishruth Devan
  description: "Vishruth's personal website"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  ShowToc: false
  TocOpen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16:
    favicon32x32:
    apple_touch_icon: "favicon.ico"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "home"
    icon: "images/icon.png"
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Vishruth Devan
    subtitle: "software engineer"
    imageUrl: "images/profile.png"
    imageWidth: 180
    imageHeight: 180
    imageTitle: kingdom in blue
    # buttons:
    #   - name: About
    #     url: about

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/vishruthdevan/"
    - name: twitter
      url: "https://twitter.com/vishruthdevan/"
    - name: linkedin
      url: "https://www.linkedin.com/in/vishruthdevan/"
    - name: instagram
      url: "https://www.instagram.com/vishruth.devan/"
    - name: email
      url: "mailto:vishruthdevan@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "G-B286V2NHY6"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  # URL: "https://github.com/<path_to_repo>/content"
  # Text: "Suggest Changes" # edit text
  # appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifies: about
      name: about
      url: /about/
      weight: 10
    - identifier: education
      name: education
      url: /education/
      weight: 20
    - identifier: experience
      name: experience
      url: /experience/
      weight: 30
    - identifier: projects
      name: projects
      url: /projects/
      weight: 40
    - identifier: poems
      name: poems
      url: /poems/
      weight: 50
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 50
    - identifier: resume
      name: resume
      url: https://drive.google.com/file/d/1OP_N_S2l5pUGqzloqg_aEG5Qiazjjldk/view?usp=sharing
      weight: 60

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: monokai
